name: Ansible Syntax Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.14'

      - name: Install Ansible and Linter
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint

      - name: Run Ansible Syntax Check
        run: |
          ansible-playbook -i hosts.ini docker_setup.yml --syntax-check

      - name: Run Ansible Lint
        run: |
          ansible-lint docker_setup.yml