---
- name: Automatic Docker setup
  hosts: webservers
  become: true

  tasks:
    - name: 1. Install Docker and Python library
      ansible.builtin.apt:
        name:
          - docker.io
          - python3-docker
        state: present
        update_cache: true

    - name: 2. Docker status check
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: 3. Download and run a Docker container
      community.docker.docker_container:
        name: first_container
        image: nginx:latest
        state: started
        restart_policy: always
        ports:
          - "8080:80"